### ISSUE TITLE
segbot_navigation: amcl max range

### ISSUE THREAD

**Issue by piyushk** [utexas-bwi/segbot_apps#31]
In the new version of the code, the amcl max range was changed to -1.0. -1.0 means the max range reported by the sensor should be used.

It seems like the 20m laser returns a max range of 60m, and localization suffers at this value. Change the max range for segbot_v2 to 20m and segbot_v1 to 4m using explicit parameter instantiation.

**Comment by jack-oquin** [comment]
Is there some way to convince both lasers to report max range correctly? That seems like the best solution.

**Comment by piyushk** [comment]
The laser does technically have a max range of 60m. It's just that we don't quite often see readings past 20m, and doing amcl scan matching all the way up to 60m can be detrimental.

That being said, I did not find a way to reduce the max range for the laser at the driver level.
