### ISSUE TITLE
segbot_logical_translator: rename package and move to bwi_common?

### ISSUE THREAD

**Issue by jack-oquin** [utexas-bwi/segbot_apps#33]
As far as I can tell, this package has nothing specifically to do with the segbot platform. It only depends on bwi_common packages and other low-level components, like multi_level_map.

Perhaps I am missing some reason why it needs to be segbot-specific?

At any rate, this can be delayed until the end of the semester, if that seems advisable.

**Comment by piyushk** [comment]
Issue migrated to https://github.com/utexas-bwi/segbot/issues/54
